force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application</description>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Candidate lookup realtionship</description>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Job lookup realtionship</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>Interview-{0000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <label>Interview Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Offer</description>
    <label>Offer</label>
    <nameField>
        <displayFormat>Offer-{0000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RecruitmentEmailService.cls
public class RecruitmentEmailService {

    // Common method to send email
    private static void sendEmails(List<Messaging.SingleEmailMessage> emails){
        if(!emails.isEmpty()){
            Messaging.sendEmail(emails);
        }
    }

    // Shortlist Email
    public static void sendShortlistEmail(List<Id> appIds){

        List<Application__c> apps = [
            SELECT Candidate__r.Email__c, Candidate__r.Name, Job__r.Name
            FROM Application__c WHERE Id IN :appIds
        ];

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Application__c app : apps){
            Messaging.SingleEmailMessage m = new Messaging.SingleEmailMessage();
            m.setToAddresses(new String[]{app.Candidate__r.Email__c});
            m.setSubject('Application Shortlisted');
            m.setPlainTextBody('Hello ' + app.Candidate__r.Name +
                ', Your application for ' + app.Job__r.Name + ' is shortlisted.');
            emails.add(m);
        }

        sendEmails(emails);
    }

    // Application Rejected
    public static void sendApplicationRejectedEmail(List<Id> appIds){

        List<Application__c> apps = [
            SELECT Candidate__r.Email__c, Candidate__r.Name
            FROM Application__c WHERE Id IN :appIds
        ];

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Application__c app : apps){
            Messaging.SingleEmailMessage m = new Messaging.SingleEmailMessage();
            m.setToAddresses(new String[]{app.Candidate__r.Email__c});
            m.setSubject('Application Rejected');
            m.setPlainTextBody('Hello ' + app.Candidate__r.Name +
                ', We regret to inform you that your application was not selected.');
            emails.add(m);
        }

        sendEmails(emails);
    }

    // Interview Scheduled
    public static void sendInterviewScheduledEmail(List<Id> ids){

        List<Interview__c> listData = [
            SELECT Interview_Date__c,
                   Application__r.Candidate__r.Email__c,
                   Application__r.Candidate__r.Name,
                   Application__r.Job__r.Name
            FROM Interview__c WHERE Id IN :ids
        ];

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Interview__c i : listData){
            Messaging.SingleEmailMessage m = new Messaging.SingleEmailMessage();
            m.setToAddresses(new String[]{i.Application__r.Candidate__r.Email__c});
            m.setSubject('Interview Scheduled');
            m.setPlainTextBody('Hello ' + i.Application__r.Candidate__r.Name +
                ', Interview for ' + i.Application__r.Job__r.Name +
                ' on ' + i.Interview_Date__c );
            emails.add(m);
        }

        sendEmails(emails);
    }

    //  Interview Rescheduled
    public static void sendInterviewUpdateEmail(List<Id> ids){
        sendInterviewScheduledEmail(ids);
    }

    //  Interview Failed
    public static void sendInterviewFailEmail(List<Id> ids){

        List<Interview__c> listData = [
            SELECT Application__r.Candidate__r.Email__c,
                   Application__r.Candidate__r.Name
            FROM Interview__c WHERE Id IN :ids
        ];

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Interview__c i : listData){
            Messaging.SingleEmailMessage m = new Messaging.SingleEmailMessage();
            m.setToAddresses(new String[]{i.Application__r.Candidate__r.Email__c});
            m.setSubject('Interview Result');
            m.setPlainTextBody('Hello ' + i.Application__r.Candidate__r.Name +
                ', Unfortunately, you did not clear the interview.');
            emails.add(m);
        }

        sendEmails(emails);
    }

    // Offer Created
    public static void sendOfferCreatedEmail(List<Id> ids){

        List<Offer__c> listData = [
            SELECT Application__r.Candidate__r.Email__c,
                   Application__r.Candidate__r.Name
            FROM Offer__c WHERE Id IN :ids
        ];

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Offer__c o : listData){
            Messaging.SingleEmailMessage m = new Messaging.SingleEmailMessage();
            m.setToAddresses(new String[]{o.Application__r.Candidate__r.Email__c});
            m.setSubject('Offer Created');
            m.setPlainTextBody('Hello ' + o.Application__r.Candidate__r.Name +
                ', Your offer has been created. Please login to Accept/Reject.');
            emails.add(m);
        }

        sendEmails(emails);
    }

    // Offer Accepted
    public static void sendOfferAcceptedEmail(List<Id> ids){
    
        List<Offer__c> offers = [
            SELECT Id,
                   Application__r.Candidate__r.Email__c,
                   Application__r.Candidate__r.Name,
                   Application__r.Job__r.Name
            FROM Offer__c
            WHERE Id IN :ids
        ];
    
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
    
        for(Offer__c offer : offers){
    
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    
            mail.setToAddresses(new String[]{
                offer.Application__r.Candidate__r.Email__c
            });
    
            mail.setSubject('Welcome to the Company 🎉');
    
            mail.setPlainTextBody(
                'Hello ' + offer.Application__r.Candidate__r.Name + ',\n\n' +
                'Congratulations! We are excited to welcome you to our organization.\n\n' +
                'Your offer for the position of ' + offer.Application__r.Job__r.Name + ' has been accepted successfully.\n\n' +
                'Our HR team will contact you shortly with onboarding details.\n\n' +
                'We look forward to working with you!\n\n' +
                'Best Regards,\nRecruitment Team'
            );
    
            emails.add(mail);
        }
    
        if(!emails.isEmpty()){
            Messaging.sendEmail(emails);
        }
     }

    // Offer Rejected
    public static void sendOfferRejectedEmail(List<Id> ids){

        List<Offer__c> offers = [
            SELECT Id,
                   Application__r.Candidate__r.Email__c,
                   Application__r.Candidate__r.Name,
                   Application__r.Job__r.Name
            FROM Offer__c
            WHERE Id IN :ids
        ];
    
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
    
        for(Offer__c offer : offers){
    
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    
            mail.setToAddresses(new String[]{
                offer.Application__r.Candidate__r.Email__c
            });
    
            mail.setSubject('Regarding Your Offer Decision');
    
            mail.setPlainTextBody(
                'Hello ' + offer.Application__r.Candidate__r.Name + ',\n\n' +
                'Thank you for considering our offer for the position of ' + offer.Application__r.Job__r.Name + '.\n\n' +
                'We respect your decision to decline the offer.\n\n' +
                'We truly appreciate your time and interest in our organization.\n\n' +
                'We wish you all the best in your future endeavors.\n\n' +
                'Regards,\nRecruitment Team'
            );
    
            emails.add(mail);
        }
    
        if(!emails.isEmpty()){
            Messaging.sendEmail(emails);
        }
    }

    // Offer (Interview Pass)
    public static void sendOfferEmail(List<Id> ids){

        List<Interview__c> listData = [
            SELECT Application__r.Candidate__r.Email__c,
                   Application__r.Candidate__r.Name
            FROM Interview__c WHERE Id IN :ids
        ];

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Interview__c i : listData){
            Messaging.SingleEmailMessage m = new Messaging.SingleEmailMessage();
            m.setToAddresses(new String[]{i.Application__r.Candidate__r.Email__c});
            m.setSubject('Interview Passed');
            m.setPlainTextBody('Congratulations! You passed the interview.');
            emails.add(m);
        }

        sendEmails(emails);
    }
}