force-app/main/default/objects/Candidate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateController.cls
public with sharing class CandidateController {

    @AuraEnabled(cacheable=true)
    public static Candidate__c getCandidate(Id userId) {
        List<Candidate__c> candidates = [
            SELECT Id, Name
            FROM Candidate__c
            WHERE User__c = :userId
            LIMIT 1
        ];
        if(!candidates.isEmpty()){
            return candidates[0];
        }
        return null;
    }
}