force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>Interview-{0000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <label>Interview Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InterviewTriggerHandler.cls
public class InterviewTriggerHandler {
    public static void afterInsert(List<Interview__c> newInterviews){
        List<Id> ids = new List<Id>();
        for(Interview__c i : newInterviews){
            ids.add(i.Id);
        }
        RecruitmentEmailService.sendInterviewScheduledEmail(ids);
    }
    public static void afterUpdate(List<Interview__c> newList, Map<Id, Interview__c> oldMap){
        List<Id> rescheduledIds = new List<Id>();
        List<Id> passedIds = new List<Id>();
        List<Id> failedIds = new List<Id>();
        for(Interview__c i : newList){
            Interview__c oldI = oldMap.get(i.Id);

            if(i.Interview_Date__c != oldI.Interview_Date__c){
                rescheduledIds.add(i.Id);
            }

            if(i.Result__c == 'Pass' && oldI.Result__c != 'Pass'){
                passedIds.add(i.Id);
            }

            if(i.Result__c == 'Fail' && oldI.Result__c != 'Fail'){
                failedIds.add(i.Id);
            }
        }
        if(!rescheduledIds.isEmpty()){
            RecruitmentEmailService.sendInterviewUpdateEmail(rescheduledIds);
        }
        if(!passedIds.isEmpty()){
            RecruitmentEmailService.sendOfferEmail(passedIds);
        }
        if(!failedIds.isEmpty()){
            RecruitmentEmailService.sendInterviewFailEmail(failedIds);
        }
    }
}